In [4]:
import os
from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import CharacterTextSplitter
from langchain_openai import ChatOpenAI
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_chroma import Chroma

In [5]:
from dotenv import load_dotenv

load_dotenv()

True

In [6]:
import pandas as pd

books = pd.read_csv("books_cleaned.csv")

In [7]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883 A NOVEL THAT READERS and critics...
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine..."
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,The Four Loves,9780006280897 Lewis' work on the nature of lov...
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,0.0,Mistaken Identity,9788172235222 On A Train Journey Home To North...
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,Journey to the East,9788173031014 This book tells the tale of a ma...
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Passi...
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,The Berlin Phenomenology,9789027712059 Since the three volume edition o...

In [8]:
books["tagged_description"]

0       9780002005883 A NOVEL THAT READERS and critics...
1       9780002261982 A new 'Christie for Christmas' -...
2       9780006178736 A memorable, mesmerizing heroine...
3       9780006280897 Lewis' work on the nature of lov...
4       9780006280934 "In The Problem of Pain, C.S. Le...
                              ...
5192    9788172235222 On A Train Journey Home To North...
5193    9788173031014 This book tells the tale of a ma...
5194    9788179921623 Wisdom to Create a Life of Passi...
5195    9788185300535 This collection of the timeless ...
5196    9789027712059 Since the three volume edition o...
Name: tagged_description, Length: 5197, dtype: str

In [9]:
books["tagged_description"].to_csv("tagged_description.txt",
                                   sep = "\n",
                                   index = False,
                                   header = False)

In [10]:
raw_documents = TextLoader("tagged_description.txt", encoding="utf-8").load()
text_splitter = CharacterTextSplitter(chunk_size=8000, chunk_overlap=0, separator="\n")
documents = text_splitter.split_documents(raw_documents)

In [11]:
documents[0]

Document(metadata={'source': 'tagged_description.txt'}, page_content='9780002005883 A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.\n9780002261982 A new \'Christie for Christmas\' -- a full-length novel adapted from her acclaimed play by Charles Osborne Following BLACK COFFEE and THE UNEXPECTED GUEST comes the final Agatha Christie play novelisation, bringing her superb storytelling to a new legion of fans. Clarissa, the wife of a Foreign Office diplomat, is given to daydreaming. \'Supposing I were to come down one morning and find a dead body in the library, what should I do?\' she muses. Clarissa has her chance to find out when she discovers a body in the drawing-room of her house in Kent. Desperate to dispose of the body before her husband comes home with an important foreign politician, Clarissa persuades her three house guests to become accessories and accomplices. It seems that the murdered man was not unknown to certain members of the house party (but which ones?), and the search begins for the murderer and the motive, while at the same time trying to persuade a police inspector that there has been no murder at all... SPIDER\'S WEB was written in 1954 specifically for Margaret Lockwood and opened first at the Theatre Royal Nottingham before moving to the Savoy Theatre in London on 14 December 1954. With THE MOUSETRAP and WI\n9780006178736 A memorable, mesmerizing heroine Jennifer -- brilliant, beautiful, an attorney on the way up until the Mafia\'s schemes win her the hatred of an implacable enemy -- and a love more destructive than hate. A dangerous, dramatic world The Dark Arena of organized crime and flashbulb lit courtrooms where ambitious prosecutors begin their climb to political power.\n9780006280897 Lewis\' work on the nature of love divides love into four categories; Affection, Friendship, Eros and Charity. The first three come naturally to humanity. Charity, however, the Gift-love of God, is divine, and without this supernatural love, the natural loves become distorted and even dangerous.\n"9780006280934 ""In The Problem of Pain, C.S. Lewis, one of the most renowned Christian authors and thinkers, examines a universally applicable question within the human condition: If God is good and all-powerful, why does he allow his creatures to suffer pain? With his signature wealth of compassion and insight, C.S. Lewis offers answers to these crucial questions and shares his hope and wisdom to help heal a world hungering for a true understanding of human nature.""--Amazon."\n9780006380832 Until Vasco da Gama discovered the sea-route to the East in 1497-9 almost nothing was known in the West of the exotic cultures and wealth of the Indian Ocean and its peoples. It is this civilization and its destruction at the hands of the West that Richard Hall recreates in this book. Hall\'s history of the exploration and exploitation by Chinese and Arab travellers, and by the Portuguese, Dutch and British alike is one of brutality, betrayal and colonial ambition.\n9780006470229 A new-cover reissue of the fourth book in the bestselling five-volume sf series created by the world-famous author of the Thomas Covenant chronicles -- and acclaimed as the \'best work of his career\'. Events were not moving as the Amnion had intended. Once again humans had been false in their dealings with the aliens. As the planetoid Thanatos Minor exploded into atoms, the Trumpet hurtled into space only one step ahead of hostile pursuers. On board were Morn Hyland and her force-grown son Davies, cyborg Angus Thermopyle and Captain Nick Succorso -- old enemies thrown together in a desperate bid for survival. For both the Amnion and the UMCP, the immediate capture of the fleeing ship and the secrets it contained was imperative. But for Trumpet\'s exhausted crew the only hope lay in an illegal lab in the distant binary solar system of Valdor Industrial. It would be a journey of unpredictable danger -- from which not all would return...\n9780006472612 Kate Blackwell is an enigma and one of the most powerful women in the world. But at her ninetieth birthday celebrations there are ghosts of absent friends and absent enemies.\n9780006482079 Tricked once more by his wily half-brother, Lysaer, Lord of Light, arrives at the tiny harbor town of Merior to find that Arithon\'s ship yards have been abandoned and meticulously destroyed, and that the Master of Shadow has disappeared as if into thin air. Meanwhile Arithon and the Mad Prophet Dakar are traveling on foot through the treacherous Kelhorn Mountains towards the Vastmark clans, there to raise further support for his cause. But raising a warhost is a costly business. Is it mere coincidence that Princess Talith—Lysaer\'s beautiful, headstrong wife—is taken captive and held for a vast ransom by a master brigand? The forces of light and shadow circle and feint, drawing ever closer to a huge conflict. And in the background the Fellowship of Seven Sorcerers and the Koriani Enchantresses watch and plan, and wait.\n"9780006483014 An omnibus volume of the author\'s complete story of the Arthurian epic which includes: ""The sword in the stone"" (1939), ""The witch in the wood"" (1939), ""The ill-made knight"" (1940), ""The candle in the wind"" (published for the first time), and ""The book of Merlyn."" 1996."\n"9780006483892 Available in the U.S. for the first time, this is the second volume in the exceptional Legends of the Riftwar series from ""New York Times""-bestselling authors Feist and Rosenberg."\n"9780006483908 Jimmy the Hand, boy thief of Krondor, lived in the shadows of the city. Though gifted beyond his peers, Jimmy is merely a pickpocket with potential--until he aids Prince Arutha in the rescue of Princess Anita from Duke Guy du Bas-Tyra, and runs afoul of ""Black Guy\'s"" secret police. Facing a choice between disappearing on his own or in a weighted barrel at the bottom of Krondor\'s harbor, Jimmy chooses the former. Forced to flee the only home he\'s ever known, Jimmy finds himself among the unsuspecting rural villagers of Land\'s End, where he hopes to prosper with his talents for con and thievery. But Land\'s End is home to many who tread the crooked path--and to a dark, dangerous presence even the local smugglers don\'t recognize. And suddenly Jimmy\'s youthful bravado and courage are leading him into the maw of chaos . . . and, quite possibly, to his doom."')

In [12]:
embeddings = HuggingFaceEmbeddings(model_name="BAAI/bge-small-en-v1.5")

llm = ChatOpenAI(
    model='deepseek-chat',
    api_key=os.getenv("DEEPSEEK_API_KEY"),
    base_url='https://api.deepseek.com',
    max_tokens=1024
)

db_books = Chroma.from_documents(
    documents,
    embedding=embeddings,
    persist_directory="./chroma_db"
)

In [13]:
query = "A book to teach children about nature"
docs = db_books.similarity_search(query, k = 10)
docs

[Document(id='ab2a7619-efa8-44bd-ac47-b79c65fbb6cd', metadata={'source': 'tagged_description.txt'}, page_content='9780974607894 This vivid, sensitive tale of adolescent love follows a 16-year-old boy who falls in love with a beautiful, older woman and experiences a whirlwind of changing emotions, from exaltation and jealousy to despair and devotion. This beautifully packaged series of classic novellas includes the works of masterful writers. Inexpensive and collectible, they are the first single-volume publications of these classic tales, offering a closer look at this under-appreciated literary form and providing a fresh take on the world\'s most celebrated authors.\n"9780975323113 Gardening. Environmental Studies. Photographs by Saxon Holt. Illustrations by Richard Pembroke. This lavishly illustrated book celebrates the challenges and opportunities of gardening in Mediterranean climates, with special reference to northern California\'s San Francisco Bay Region. The core of the book is a catalog of more than 650 plants suited to regions with mild, usually wet winters and dry, often hot summers. These plants thrive with moderate to no summer irrigation when established, require little or no maintenance, and are reasonably available from nurseries, botanic gardens, native plant sales, or specialty seed suppliers. Many of the 542 color photographs show plants in garden settings to suggest attractive and compatible plant combinations. Summary charts provide information on each plant, such as bloom time, needs for water and sun, and preferences for coastal or inland microclimates. Lists suggest plants for special situations, such as hot sites, dryish shade, small gardens, and clay soils. Chapters on landscape design and maintenance inspire readers to make gardens that use little water and no harmful chemicals, with a focus on building healthy soil. Practical steps to successful design are supplemented with ideas for designing with microclimate, attracting wildlife, and fire safety. Sidebars by local experts discuss weather, natural landscapes, design solutions, and gardening with recycled water. ""A valuable resource for climate-compatible gardening in the San Franciso Bay Area that will also be of interest to gardeners in other parts of the world with a similar seasonal pattern of winter rain and dry summers. This book will occupy a prominent place in my library for many years to come.""—Katherine Greenberg, president Mediterranean Garden Society ""This book is beautifully designed with abundant photographs of plants, many in garden settings, and it is packed with the kind of information gardeners need for their own special situations. Simply stunning! Bravo!""—Phyllis M. Faber, editor University of California Press"\n9780976072614 This complete edition of Caesar\'s Commentaries contains all eight of Caesar\'s books on the Gallic War as well as all three of his books on the Civil War masterfully translated into English by W. A. MacDevitt. Caesar\'s Commentaries are an outstanding account of extraordinary events by one of the most exceptional men in the history of the world. Julius Caesar himself was one of the most eminent writers of the age in which he lived. His commentaries on the Gallic and Civil Wars are written with a purity, precision, and perspicuity, which command approbation. They are elegant without affectation, and beautiful without ornament. Of the two books which he composed on Analogy, and those under the title of Anti-Cato, scarcely any fragment is preserved; but we may be assured of the justness of the observations on language, which were made by an author so much distinguished by the excellence of his own compositions. His poem entitled The Journey, which was probably an entertaining narrative, is likewise totally lost. All of Caesar\'s works that remain intact are contained in this edition of his commentaries. It is to the honor of Caesar, that when he had obtained the supreme power, he exercised it with a degree of moderation beyond what was generally expected by those who had fought on the side of the Republic. His time was almost entirely occupied with public affairs, in the management of which, though he employed many agents, he appears to have had none in the character of actual minister. Caesar deprecated a lingering death, and wished that his own might be sudden and speedy. And the day before he died, the conversation at supper, in the house of Marcus Lepidus, turning upon what wasthe most eligible way of dying, he gave his opinion in favor of a death that is sudden and unexpected. He died in the fifty-sixth year of his age, and was ranked amongst the Gods.\n9780976249870 For God so loved the world that he gave his only two begotten sons. and a few million zombies Thugs, pushers, gangsters, rapists, murderers; Detective Philip Makane thought he\'d seen it all until he awoke on the morning of Easter Sunday 2015, to a world filled with bleeding rain, ravenous zombies, a homicidal ghost, and the sudden arrival of two men with extraordinary powers who both claim to be Jesus Christ in the flesh.\n"9780976540601 Through the magic of print-on-demand technology, this ""nimble"" guide to the work of best-selling author J. K. Rowling provides the latest news about the author and her works, updated whenever there are significant developments. Unlike a conventional book, for which editions are printed in quantity every couple of years, this ""living book"" goes through frequent ""mini-editions"" and is printed fresh whenever customers place an order. Purchasers are entitled to free PDF updates! An entirely new section of analysis with more than 75 new pages will be added shortly after the release of ""Harry Potter and the Half-Blood Prince"" on July 16, 2005."\n"9780976631156 Clown Girl lives in Baloneytown, a seedy neighborhood where drugs, balloon animals, and even rubber chickens contribute to the local currency. Against a backdrop of petty crime, she struggles to live her dreams, calling on cultural masters Charlie Chaplin, Kafka, and da Vinci for inspiration. In an effort to support herself and her layabout performance-artist boyfriend, Clown Girl finds herself unwittingly transformed into a ""corporate clown,"" trapping herself in a cycle of meaningless, high-paid gigs that veer dangerously close to prostitution. Monica Drake has created a novel that riffs on the high comedy of early film stars — most notably Chaplin and W. C. Fields — to raise questions of class, gender, economics, and prejudice. Resisting easy classification, this debut novel blends the bizarre, the humorous, and the gritty with stunning skill."'),
 Document(id='583a9d23-9de4-4c15-bf0a-3c8ce577ed56', metadata={'source': 'tagged_description.txt'}, page_content='"9780067575208 First published more than three decades ago, this reissue of Rachel Carson\'s award-winning classic brings her unique vision to a new generation of readers. Stunning new photographs by Nick Kelsh beautifully complement Carson\'s intimate account of adventures with her young nephew, Roger, as they enjoy walks along the rocky coast of Maine and through dense forests and open fields, observing wildlife, strange plants, moonlight and storm clouds, and listening to the ""living music"" of insects in the underbrush. ""If a child is to keep alive his inborn sense of wonder."" Writes Carson, ""he needs the companionship of at least one adult who can share it, rediscovering with him the joy, excitement and mystery of the world we live in."" The Sense of Wonder is a refreshing antidote to indifference and a guide to capturing the simple power of discovery that Carson views as essential to life. In her insightful new introduction, Linda Lear remembers Rachel Carson\'s groundbreaking achievements in the context of the legendary environmentalist\'s personal commitment to introducing young and old to the miracles of nature. Kelsh\'s lush photographs inspire sensual, tactile reactions: masses of leaves floating in a puddle are just waiting to be scooped up and examined more closely. An image of a narrow path through the trees evokes the earthy scent of the woods after a summer rain. Close-ups of mosses and miniature lichen fantasy-lands will spark innocent\'as well as more jaded\'imaginations. Like a curious child studying things underfoot and within reach, Kelsh\'s camera is drawn to patterns in nature that too often elude hurried adults\'a stand of beech trees in the springtime, patches of melting snow and the ripples from a pebble tossed into a slow-moving stream. The Sense of Wonder is a timeless volume that will be passed on from children to grandchildren, as treasured as the memory of an early-morning walk when the song of a whippoorwill was heard as if for the first time."\n9780070488205 The Blessed Virgin\'s deliverance of a prophecy to a peasant girl in Fatima in 1914 is followed years later by signs and omens including worldwide droughts and famines that signify its imminent fulfillment\n9780071348270 Explains how to improve one\'s existing organization while creating a replacement design for the future and why change is necessary to ensure the future of one\'s business\n9780071401944 The New York Times Bestseller! Learn how to keep your cool and get the results you want when emotions flare. When stakes are high, opinions vary, and emotions run strong, you have three choices: Avoid a crucial conversation and suffer the consequences; handle the conversation badly and suffer the consequences; or read Crucial Conversations and discover how to communicate best when it matters most. Crucial Conversations gives you the tools you need to step up to life\'s most difficult and important conversations, say what\'s on your mind, and achieve the positive resolutions you want. You\'ll learn how to: Prepare for high-impact situations with a six-minute mastery technique Make it safe to talk about almost anything Be persuasive, not abrasive Keep listening when others blow up or clam up Turn crucial conversations into the action and results you want Whether they take place at work or at home, with your neighbors or your spouse, crucial conversations can have a profound impact on your career, your happiness, and your future. With the skills you learn in this book, you\'ll never have to worry about the outcome of a crucial conversation again.\n"9780071418584 ""You\'ll not only break the ice, you\'ll melt it away with your new skills."" -- Larry King ""The lost art of verbal communication may be revitalized by Leil Lowndes."" -- Harvey McKay, author of “How to Swim with the Sharks Without Being Eaten Alive” What is that magic quality makes some people instantly loved and respected? Everyone wants to be their friend (or, if single, their lover!) In business, they rise swiftly to the top of the corporate ladder. What is their ""Midas touch?"" What it boils down to is a more skillful way of dealing with people. The author has spent her career teaching people how to communicate for success. In her book How to Talk to Anyone (Contemporary Books, October 2003) Lowndes offers 92 easy and effective sure-fire success techniques-- she takes the reader from first meeting all the way up to sophisticated techniques used by the big winners in life. In this information-packed book you’ll find: 9 ways to make a dynamite first impression 14 ways to master small talk, ""big talk,"" and body language 14 ways to walk and talk like a VIP or celebrity 6 ways to sound like an insider in any crowd 7 ways to establish deep subliminal rapport with anyone 9 ways to feed someone\'s ego (and know when NOT to!) 11 ways to make your phone a powerful communications tool 15 ways to work a party like a politician works a room 7 ways to talk with tigers and not get eaten alive In her trademark entertaining and straight-shooting style, Leil gives the techniques catchy names so you\'ll remember them when you really need them, including: ""Rubberneck the Room,"" ""Be a Copyclass,"" ""Come Hither Hands,"" “Bare Their Hot Button,” “The Great Scorecard in the Sky,"" and ""Play the Tombstone Game,” for big success in your social life, romance, and business. How to Talk to Anyone, which is an update of her popular book, Talking the Winner\'s Way (see the 5-star reviews of the latter) is based on solid research about techniques that work! By the way, don\'t confuse How to Talk to Anyone with one of Leil\'s previous books, How to Talk to Anybody About Anything. This one is completely different!"\n9780071428484 The fun and easy way to quickly enhance your French reading skills Easy French Reader is based on the premise that the best way to learn a language is to start reading it, immediately. Suitable for raw beginners to intermediate-level language learners, this popular title features engaging readings of progressive difficulty that allow you to rapidly build your comprehension. Find out what unfamiliar words and phrases mean with the book\'s helpful glossary Discover the nuances of French language and culture as well as the country\'s history through engaging texts Get a feel for authentic French society with readings from contemporary literature\n"9780071433716 ""A young woman\'s fatal battle with anorexia, in her own words In the tradition of Go Ask Alice, Prozac Nation, and Girl Interrupted, Slim to None grants readers precious access to the emotional and psychological underpinnings of its author. Step-by-step, readers follow Jenny\'s long journey through a ""wasteland"" of failed treatments and therapies, false hope, and abuse by the mental health system that kept her captive most of her life. Although this disease has been at the forefront of public awareness for years, anorexia continues to claim more victims than any other mental illness. Slim to None reveals the glaring inadequacy of the mental health system to treat and fully understand this disease. The first journal of an anorexic to be published posthumously, the book discloses the innermost thoughts, fears, and hopes of a young girl stricken and fighting to recover. Jenny Hendricks painstakingly recorded her experiences as she suffered from and eventually succumbed to this eating disorder. With candor, she recounts being shipped from one doctor to another and subjected to widely varying treatments--all of which ultimately proved unsuccessful. Her father, Gordon Hendricks, fills in this compelling narrative with his own memories of his daughter\'s struggle.""--Publisher\'s description."'),

In [14]:
books[books["isbn13"] == int(docs[0].page_content.strip('"').split()[0])]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
4294,9780974607894,0974607894,First Love,Ivan Sergeevich Turgenev,Fiction,http://books.google.com/books/content?id=VcNvD...,"This vivid, sensitive tale of adolescent love ...",2004.0,3.79,124.0,5551.0,First Love,"9780974607894 This vivid, sensitive tale of ad..."

In [15]:
def retrieve_semantic_recommendations(
        query: str,
        top_k: int = 10,
) -> pd.DataFrame:
    recs = db_books.similarity_search(query, k = 50)

    books_list = []

    for i in range(0, len(recs)):
        books_list += [int(recs[i].page_content.strip('"').split()[0])]

    return books[books["isbn13"].isin(books_list)]

In [16]:
retrieve_semantic_recommendations("A book to teach children about nature")

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
80,9780020867401,0020867409,"The Screwtape Letters ; With, Screwtape Propos...",Clive Staples Lewis,Christianity,NaN,One of C.S. Lewis's most imaginative creations...,1982.0,4.22,172.0,313.0,"The Screwtape Letters ; With, Screwtape Propos...",9780020867401 One of C.S. Lewis's most imagina...
106,9780060256753,0060256753,"Lafcadio, the Lion Who Shot Back",Shel Silverstein,Juvenile Fiction,http://books.google.com/books/content?id=lmeJR...,"""You don't have to shoot me,"" says the young l...",1963.0,4.15,112.0,5191.0,"Lafcadio, the Lion Who Shot Back","9780060256753 ""You don't have to shoot me,"" sa..."
146,9780060556501,0060556501,"The Lion, the Witch and the Wardrobe (picture ...",C. S. Lewis,Juvenile Fiction,http://books.google.com/books/content?id=FlSpp...,Narnia: A magical land full of wonder and exci...,2004.0,4.19,48.0,5012.0,"The Lion, the Witch and the Wardrobe (picture ...",9780060556501 Narnia: A magical land full of w...
187,9780060645892,006064589X,The Dance of the Dissident Daughter,Sue Monk Kidd,Religion,http://books.google.com/books/content?id=0FV3J...,The acclaimed spiritual memoir from the author...,2002.0,3.96,256.0,5319.0,The Dance of the Dissident Daughter,9780060645892 The acclaimed spiritual memoir f...
367,9780061124266,0061124265,Veronika Decides to Die,Paulo Coelho,Fiction,http://books.google.com/books/content?id=dlgK3...,Twenty-four-year-old Veronika seems to have ev...,2006.0,3.70,210.0,126224.0,Veronika Decides to Die: A Novel of Redemption,9780061124266 Twenty-four-year-old Veronika se...
404,9780064402453,0064402452,Racso and the Rats of NIMH,Jane Leslie Conly,Juvenile Fiction,http://books.google.com/books/content?id=MgoNv...,"‘Racso, a brash and boastful little rodent, is...",1988.0,3.76,288.0,3231.0,Racso and the Rats of NIMH,"9780064402453 ‘Racso, a brash and boastful lit..."
420,9780064408677,0064408671,The Trumpet of the Swan,E. B. White,Juvenile Fiction,http://books.google.com/books/content?id=2lybT...,"Swan Song Like the rest of his family, Louis i...",2000.0,4.07,252.0,61304.0,The Trumpet of the Swan,9780064408677 Swan Song Like the rest of his f...
434,9780064462044,0064462048,My Little House Crafts Book,Carolyn Strom Collins,Juvenile Nonfiction,http://books.google.com/books/content?id=lTzrs...,Make the same pioneer crafts that Laura did! I...,1998.0,4.05,64.0,56.0,My Little House Crafts Book: 18 Projects from ...,9780064462044 Make the same pioneer crafts tha...
442,9780067575208,006757520X,The Sense of Wonder,Rachel Carson,Nature,http://books.google.com/books/content?id=Zee5S...,"First published more than three decades ago, t...",1998.0,4.39,112.0,1160.0,The Sense of Wonder,9780067575208 First published more than three ...
449,9780071451383,0071451382,Practice Makes Perfect: Italian Verb Tenses,Paola Nanni-Tate,Foreign Language Study,http://books.google.com/books/content?id=Mbix2...,Practice makes perfect Italian verb tenses goe...,2005.0,4.00,252.0,9.0,Practice Makes Perfect: Italian Verb Tenses,9780071451383 Practice makes perfect Italian v...
549,9780131871656,013187165X,Astronomy,Eric Chaisson;Stephen McMillan,Mathematics,http://books.google.com/books/content?id=1O00A...,This introduction to astronomy features an exc...,2006.0,3.85,499.0,153.0,Astronomy: a beginner's guide to the universe,9780131871656 This introduction to astronomy f...
991,9780192862099,019286209X,The Origins of Life,John Maynard Smith;Eörs Szathmáry,Science,http://books.google.com/books/content?id=nHDbB...,'I can recommend this book as a thoroughly int...,2000.0,4.11,192.0,41.0,The Origins of Life: From the Birth of Life to...,9780192862099 'I can recommend this book as a ...
1007,9780195169249,0195169247,Introduction to Philosophy,John Perry;Michael Bratman;John Martin Fischer,Philosophy,http://books.google.com/books/content?id=h0zuA...,"Introduction to Philosophy, Fourth Edition, is...",2007.0,3.76,819.0,12.0,Introduction to Philosophy: Classical and Cont...,"9780195169249 Introduction to Philosophy, Four..."
1120,9780300091694,0300091699,Dreaming in Pictures,Douglas Robert Nickel;Lewis Carroll;San Franci...,Photography,http://books.google.com/books/content?id=Jpnz4...,"""Lewis Carroll was the pen name of the Reveren...",2002.0,4.01,172.0,105.0,Dreaming in Pictures: The Photography of Lewis...,"9780300091694 ""Lewis Carroll was the pen name ..."
1373,9780321276230,032127623X,Essentials of American Government,Karen O'Connor;Larry J. Sabato,Political Science,http://books.google.com/books/content?id=ml8rg...,The Essentials edition of the number one book ...,2005.0,3.50,604.0,4.0,Essentials of American Government: Continuity ...,9780321276230 The Essentials edition of the nu...
1434,9780340831205,0340831200,The Art of Happiness at Work,Dalai Lama XIV Bstan-ʼdzin-rgya-mtsho;Howard C...,Buddhism,http://books.google.com/books/content?id=gQqON...,Following the massive success of THE ART OF HA...,2003.0,4.16,224.0,1583.0,The Art of Happiness at Work,9780340831205 Following the massive success of...
1735,9780375760525,0375760520,Paris 1919,Margaret MacMillan,History,http://books.google.com/books/content?id=5NYdw...,National Bestseller New York Times Editors’ Ch...,2002.0,4.07,570.0,9150.0,Paris 1919: Six Months That Changed the World,9780375760525 National Bestseller New York Tim...
1756,9780380713813,0380713810,Made in America,Bill Bryson,Language Arts & Disciplines,http://books.google.com/books/content?id=G8d_4...,"Bill Bryson, who gave glorious voice to The Mo...",1996.0,3.90,364.0,10432.0,Made in America,"9780380713813 Bill Bryson, who gave glorious v..."
1895,9780393059168,0393059162,The New Annotated Sherlock Holmes,Arthur Conan Doyle,"Detective and mystery stories, English",http://books.google.com/books/content?id=beGfD...,Collects Doyle's fifty-six classic short stori...,2005.0,4.63,1878.0,1396.0,The New Annotated Sherlock Holmes: volume 2,9780393059168 Collects Doyle's fifty-six class...
2126,9780439569729,0439569729,SCHOLASTIC SUCCESS WITH 4TH GRADE(WORKBOOK),Terry Cooper,Education,http://books.google.com/books/content?id=b-EBH...,"416 bright, colorful pages that give kids prac...",2003.0,4.57,416.0,7.0,SCHOLASTIC SUCCESS WITH 4TH GRADE(WORKBOOK),"9780439569729 416 bright, colorful pages that ..."
2176,9780440227533,0440227534,Number the Stars,Lois Lowry,Juvenile Fiction,http://books.google.com/books/content?id=IMZWo...,"In 1943, during the German occupation of Denma...",1989.0,4.13,137.0,379669.0,Number the Stars,"9780440227533 In 1943, during the German occup..."
2210,9780440418412,0440418410,The Boys Start the War,Phyllis Reynolds Naylor,Juvenile Fiction,http://books.google.com/books/content?id=fo9GH...,The first book in the hilarious trilogy featur...,2002.0,4.02,144.0,1511.0,The Boys Start the War,9780440418412 The first book in the hilarious ...
2265,9780446578271,0446578274,The Everyday Life Bible,Joyce Meyer,Bibles,http://books.google.com/books/content?id=tlPAH...,Joyce Meyer's no-nonsense approach to life and...,2006.0,4.70,2208.0,1715.0,The Everyday Life Bible: The Power of God's Wo...,9780446578271 Joyce Meyer's no-nonsense approa...
2478,9780471272427,0471272426,The Skeptic's Dictionary,Robert Carroll,Science,http://books.google.com/books/content?id=h7m6N...,A wealth of evidence for doubters and disbelie...,2003.0,4.03,446.0,522.0,The Skeptic's Dictionary: A Collection of Stra...,9780471272427 A wealth of evidence for doubter...
2504,9780486280233,0486280233,The Adventures of Jimmy Skunk,Thornton W. Burgess;Harrison Cady;Thea Kliros,Juvenile Fiction,http://books.google.com/books/content?id=dVZ8D...,Relates how Jimmy Skunk repays Peter Rabbit fo...,1994.0,4.13,96.0,258.0,The Adventures of Jimmy Skunk,9780486280233 Relates how Jimmy Skunk repays P...
2569,9780517168950,0517168952,The Crossing,Cormac McCarthy,NaN,NaN,Following All the Pretty Horses in Cormac McCa...,1996.0,4.12,425.0,226.0,The Crossing,9780517168950 Following All the Pretty Horses ...
2857,9780586210697,0586210695,The Curse of the Mistwraith,Janny Wurts,Fiction,http://books.google.com/books/content?id=Ju3E6...,"The world of Athera lives in eternal fog, its ...",2004.0,3.76,830.0,4528.0,The Curse of the Mistwraith,9780586210697 The world of Athera lives in ete...
2893,9780618057078,0618057072,The Origin of Consciousness in the Breakdown o...,Julian Jaynes,Philosophy,http://books.google.com/books/content?id=6Q0kS...,"At the heart of this classic, seminal book is ...",2000.0,4.24,491.0,3258.0,The Origin of Consciousness in the Breakdown o...,"9780618057078 At the heart of this classic, se..."
2934,9780618619078,0618619070,Bury the Chains,Adam Hochschild,History,http://books.google.com/books/content?id=8p6c9...,Offers an account of the first great human rig...,2006.0,4.27,496.0,1258.0,Bury the Chains: Prophets and Rebels in the Fi...,9780618619078 Offers an account of the first g...
2999,9780671569020,0671569023,Orchid,Jayne Castle,Fiction,http://books.google.com/books/content?id=H4CYl...,New York Times bestselling author JAYNE CASTLE...,1998.0,4.15,327.0,3654.0,Orchid,9780671569020 New York Times bestselling autho...
3037,9780674618763,0674618769,"New Worlds, Ancient Texts",Anthony Grafton;Nancy G. Siraisi;April Shelford,History,http://books.google.com/books/content?id=APVWL...,"On encountering what he called ""the Indies"", t...",1992.0,3.58,296.0,70.0,"New Worlds, Ancient Texts: The Power of Tradit...","9780674618763 On encountering what he called ""..."
3197,9780689707490,0689707495,Cloudy With a Chance of Meatballs,Judi Barrett,Juvenile Fiction,http://books.google.com/books/content?id=fQU6U...,"The beloved, bestselling tale of edible weathe...",1982.0,4.16,32.0,114747.0,Cloudy With a Chance of Meatballs,"9780689707490 The beloved, bestselling tale of..."
3229,9780691020167,0691020167,Philosophy and the Mirror of Nature,Richard Rorty,Philosophy,http://books.google.com/books/content?id=cxYFw...,Philosophy and the Mirror of Nature hit the ph...,1980.0,4.00,424.0,2720.0,Philosophy and the Mirror of Nature,9780691020167 Philosophy and the Mirror of Nat...
3291,9780739461198,0739461192,Marley and me : love and life with the world's...,John Grogan,Labrador retriever,http://books.google.com/books/content?id=IDUYo...,John and Jenny were just beginning their life ...,2005.0,4.13,291.0,406585.0,Marley and me : love and life with the world's...,9780739461198 John and Jenny were just beginni...
3473,9780747569121,0747569126,Sideways Arithmetic from Wayside School,Louis Sachar,Arithmetic,http://books.google.com/books/content?id=-oViP...,These Sideways Arithmetic problems may look pu...,2004.0,3.87,96.0,3627.0,Sideways Arithmetic from Wayside School,9780747569121 These Sideways Arithmetic proble...
3842,9780802839725,080283972X,The Early History of God,Mark S. Smith,Religion,http://books.google.com/books/content?id=1yM3A...,Foreword by Patrick D. Miller In this remarkab...,2002.0,4.06,243.0,217.0,The Early History of God: Yahweh and the Other...,9780802839725 Foreword by Patrick D. Miller In...
4102,9780838526958,0838526950,Foundations of Clinical Research,Leslie Gross Portney;Mary P. Watkins,Medical,http://books.google.com/books/content?id=zzhrA...,This book serves as a comprehensive reference ...,2000.0,4.04,742.0,17.0,Foundations of Clinical Research: Applications...,9780838526958 This book serves as a comprehens...
4176,9780873512695,0873512693,Early Candlelight,Maud Hart Lovelace,Fiction,http://books.google.com/books/content?id=XH_Ew...,"""Young Deedee DuGay knew everyone at Fort Snel...",1992.0,3.66,342.0,173.0,Early Candlelight,"9780873512695 ""Young Deedee DuGay knew everyon..."
4188,9780879232153,0879232153,Hamlet's Mill,Giorgio De Santillana;Hertha von Dechend,Philosophy,http://books.google.com/books/content?id=ql7AT...,Ever since the Greeks coined the language we c...,1977.0,4.27,450.0,458.0,Hamlet's Mill: An Essay on Myth and the Frame ...,9780879232153 Ever since the Greeks coined the...
4267,9780960989867,0960989862,The Twelve Steps and Twelve Traditions of Over...,"Overeaters Anonymous, Inc. (U.S.)",Self-Help,http://books.google.com/books/content?id=pGeWA...,Explains the twelve steps of Overeaters Anonym...,1993.0,4.37,221.0,200.0,The Twelve Steps and Twelve Traditions of Over...,9780960989867 Explains the twelve steps of Ove...
4279,9780967469782,0967469783,The Buddha in Your Mirror,Woody Hochswender;Greg Martin;Ted Morino,Religion,http://books.google.com/books/content?id=5YVEB...,While the notion that “happiness can found wit...,2001.0,4.28,230.0,704.0,The Buddha in Your Mirror: Practical Buddhism ...,9780967469782 While the notion that “happiness...
4294,9780974607894,0974607894,First Love,Ivan Sergeevich Turgenev,Fiction,http://books.google.com/books/content?id=VcNvD...,"This vivid, sensitive tale of adolescent love ...",2004.0,3.79,124.0,5551.0,First Love,"9780974607894 This vivid, sensitive tale of ad..."
4368,9781400062645,1400062640,The Secret Society of Demolition Writers,Aimee Bender;Marc Parent,Fiction,http://books.google.com/books/content?id=yK1lA...,Short stories capture the lives of such offbea...,2005.0,3.12,244.0,126.0,The Secret Society of Demolition Writers: Stories,9781400062645 Short stories capture the lives ...
4438,9781402713194,1402713193,The Secret Garden,Martha Hailey Dubose;Frances Hodgson Burnett;M...,Juvenile Fiction,http://books.google.com/books/content?id=6c9Sb...,Presents an abridged version of the tale of te...,2005.0,4.30,160.0,1346.0,The Secret Garden,9781402713194 Presents an abridged version of ...
4452,9781405151412,1405151412,How to Read a Poem,Terry Eagleton,Literary Criticism,http://books.google.com/books/content?id=mU7FZ...,"Lucid, entertaining and full of insight, How T...",2006.0,3.75,182.0,424.0,How to Read a Poem,"9781405151412 Lucid, entertaining and full of ..."
4595,9781559636629,1559636629,Marine Conservation Biology,Michael E. Soulé;Michael E. Marine Conservatio...,Nature,http://books.google.com/books/content?id=bK9Lm...,"Humans are terrestrial animals, and our capaci...",2005.0,4.67,496.0,14.0,Marine Conservation Biology: The Science of Ma...,"9781559636629 Humans are terrestrial animals, ..."
4607,9781561796779,1561796778,"Boomers, Xers, and Other Strangers",Rick Hicks;Kathy Hicks,Social Science,http://books.google.com/books/content?id=IogMA...,The authors maintain that children's core valu...,1999.0,3.36,384.0,28.0,"Boomers, Xers, and Other Strangers: Understand...",9781561796779 The authors maintain that childr...
4954,9781741040913,1741040914,London,Martin Hughes;Sarah Johnstone;Tom Masters,Travel,http://books.google.com/books/content?id=5DQXA...,This jolly good guide has elaborate descriptio...,2004.0,4.02,480.0,62.0,London,9781741040913 This jolly good guide has elabor...
5061,9781859843826,1859843824,Late Victorian Holocausts: El Nino Famines and...,Mike Davis,History,http://books.google.com/books/content?id=RQsHC...,Shows how the droughts affecting northern Afri...,2002.0,4.10,464.0,970.0,Late Victorian Holocausts: El Nino Famines and...,9781859843826 Shows how the droughts affecting...
5164,9781932664393,1932664394,Han'guk-sik Sarang,J. Torres,Comics & Graphic Novels,http://books.google.com/books/content?id=V1Fex...,"Joel, an English teacher, has never really lik...",2006.0,3.44,58.0,9.0,Han'guk-sik Sarang,"9781932664393 Joel, an English teacher, has ne..."